---
title: "Tidy Tuesday April 8, 2025"
author: "Alice Tivarovsky"
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load Libraries

```{r libs}
library(tidyverse)
library(tidytuesdayR)
library(janitor)
library(sysfonts)
library(showtext)
library(usmap)

```

## Colors & Fonts

```{r}
font_add_google("Roboto", family = "roboto_family")
showtext_auto()

```

### Load Data

```{r}
tuesdata <- tidytuesdayR::tt_load('2025-04-08')
care_state <- tuesdata$care_state
```

## Explore

Summarize variables, note missingness, note hierarchy. 
```{r}
# snapshot
care_state |> 
  head()

# states
care_state |> 
  group_by(state) |> 
  summarise(n = n()) # 56 states? 

# measure names and IDs
care_state |> 
  group_by(measure_name) |> 
  summarise(n = n()) # 21 measures

care_state |> 
  group_by(measure_id) |> 
  summarise(n = n()) # 22 measure IDs (so one duplicate)

# conditions
care_state |> 
  group_by(condition) |> 
  summarise(n = n())  # unclear why there are only 6 conditions, one of which is "Emergency Department", possibly innacurate 


# time intervals
care_state |> 
  group_by(state) |> 
  summarise(min_start_date = min(start_date), 
            min_end_date = min(end_date), 
            max_start_date = max(start_date), 
            max_end_date = max(end_date))


```

Explore measures with high variability. 
```{r}
care_state |> 
  drop_na() |> 
  group_by(measure_name) |> 
  summarise(min_score = min(score), 
            max_score = max(score))

# "Average (median) time patients spent in the emergency department before leaving from the visit- Psychiatric/Mental Health Patients. A lower number of minutes is better" is highly variable 

```


- States with longest and shortest wait times? 
- Over time? 
```{r}
wait_time <- 
  care_state |> 
  filter(measure_id == 'OP_18c', 
           !state %in% c('PR', 'GU', 'VI', 'AS', 'MP')) |> 
  arrange(state) |> 
  drop_na(score)

# dates 
min_and_max_dates <- 
  wait_time |> 
  summarise(min_date = min(start_date), 
            max_date = max(start_date))

```

## Visualize

```{r}
mean_wait_time <- mean(wait_time$score)

plot <- 
  wait_time |> 
  mutate(state = fct_reorder(state, score)) |> 
  ggplot(aes(x = score, y = state, fill = score)) + 
  geom_col(stat = "identity") + 
  scale_fill_gradient2(low = "#fe9f6d", high = "#8c2981") + 
  scale_x_continuous(expand = c(0,0))+
  geom_vline(xintercept = mean_wait_time) + # average 
  geom_text(aes(x = mean_wait_time, 
                y = 3,
                label = paste0("Average: ", round(mean_wait_time, 2)), 
                hjust = 0
                )) + 
  labs(title = "Psych/Mental Health Patients in the Northeast Spend Much Longer \nin the Emergency Room than in Other Regions",
       subtitle = "Data from CMS, 2023-2024",
       x = "Wait time (min)", 
       y = "State") + 
  theme_classic() +
  theme(text = element_text(family = "roboto_family"), 
        plot.title = element_text(color = "#b73779", size = 16), 
        legend.position = "none")

plot

```


```{r}
# plot_usmap(data = wait_time, values = "score", color = "white") + 
#   scale_fill_gradient2(low = "#fe9f6d", high = "#8c2981") + 
#  # scale_fill_continuous(low = "lightgreen", high = "darkgreen", name = "Wait Time (min)") + 
#   theme(legend.position = "right") + 
#   labs(title = "Avg Hospital Wait Times, by State", 
#        subtitle = "2023-2024 data") 

```


## Save 

```{r}
ggsave("wait_times.png", 
       plot = plot, 
       width = 7, 
       height = 5,
       units = "in",
       dpi = 150)

```

